services:
  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: fess
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: tsp_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: