version: '3.9'

services:
  db:
    image: postgres:17
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U fess -d tsp_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: tsp_db
      POSTGRES_USER: fess
      POSTGRES_PASSWORD: 12345
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

  backend:
    build: .
    command: >
      bash -c "while ! timeout 2 bash -c 'cat < /dev/null > /dev/tcp/db/5432'; do 
        sleep 2; 
      done 
      && python manage.py migrate 
      && gunicorn tsp.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/tsp
      - static_volume:/tsp/staticfiles
    networks:
      - default

volumes:
  postgres_data:
  static_volume: